#!/usr/bin/env nextflow

/*
 * human-mouse-dnds-omega/main.nf
 *
 * Real per-gene ω (pairwise dN/dS, PAML codeml) for a set of human-mouse MGI
 * ortholog pairs — feeds notebook 206's mechanism test. Percent identity (used
 * throughout notebook 206) can't distinguish "diverged under relaxed constraint"
 * from "diverged under positive selection"; ω can. This pipeline exists to
 * regress the HP-vs-protein AUC gap on ω *with percent identity as a covariate*
 * — if the ω coefficient survives that, it's a selection result, not just a
 * repackaged divergence result (see notebook 206 section 8).
 *
 * Only pairwise ω is computed (one value per gene): with just 2 taxa (human,
 * mouse) there's no statistical power for site-level tests like M7-vs-M8 or
 * MEME/FUBAR, which need a multi-taxa phylogeny. Pairwise ω is exactly the
 * quantity Ensembl used to serve genome-wide before discontinuing it at
 * Release 100 (see notebook 206's intro).
 *
 * Input: --gene_pairs, a CSV with header
 *   human_gene,human_ensg,mouse_gene,mouse_ensmusg[,source,perc_id,...]
 * (extra columns are ignored by this pipeline; notebook 206 writes them for its
 * own bookkeeping and re-joins on human_gene/mouse_gene after this pipeline
 * finishes). Generated by notebook 206 section 8, not by this pipeline — gene
 * selection depends on MGI orthology + percent-identity deciles + family
 * membership, which notebook 206 already has loaded.
 *
 * Two stages:
 *   1. fetchAllCds   — single serial process, Ensembl REST API (lookup + sequence
 *                       endpoints), rate-limited from one place, resumable.
 *   2. computeOmega   — one task per gene pair: MAFFT protein alignment -> codon
 *                       back-translation -> PAML codeml pairwise ML.
 *
 * NOT YET RUN. Written and reviewed for logic, but PAML/HyPhy weren't installed
 * anywhere reachable while writing this, so the codeml .mlc parser in
 * bin/compute_omega.py has not been checked against real PAML output. Validate
 * on `-profile test` (5 gene pairs) before trusting a full-scale run.
 */

nextflow.enable.dsl=2

params.gene_pairs   = null   // required; CSV from notebook 206 section 8
params.outdir       = 'results'
params.omega_container = 'human-mouse-dnds-omega:1.0'
params.fetch_limit  = 0      // 0 = no limit; >0 for quick manual smoke-testing

if (!params.gene_pairs) {
    error "Must specify --gene_pairs (CSV with human_gene,human_ensg,mouse_gene,mouse_ensmusg)"
}

log.info """
human-mouse-dnds-omega
  gene_pairs : ${params.gene_pairs}
  outdir     : ${params.outdir}
  container  : ${params.omega_container}
"""

process fetchAllCds {
    label 'download'
    container params.omega_container
    publishDir params.outdir, mode: 'copy', pattern: 'cds_cache/fetch_manifest.tsv'

    input:
    path gene_pairs

    output:
    path 'cds_cache', emit: cds_dir

    script:
    def limit_flag = params.fetch_limit ? "--limit ${params.fetch_limit}" : ''
    """
    fetch_cds.py --gene_pairs ${gene_pairs} --outdir cds_cache --sleep 0.15 ${limit_flag}
    """
}

process computeOmega {
    tag "${human_gene}__${mouse_gene}"
    label 'light_cpu'
    container params.omega_container
    errorStrategy 'ignore'   // one bad alignment shouldn't kill a run of hundreds

    input:
    tuple val(human_gene), val(mouse_gene), path(cds_fasta)

    output:
    path "${human_gene}__${mouse_gene}.omega.tsv"

    script:
    """
    compute_omega.py \
        --cds_fasta ${cds_fasta} \
        --human_gene ${human_gene} \
        --mouse_gene ${mouse_gene} \
        --outfile ${human_gene}__${mouse_gene}.omega.tsv \
        --workdir work_${human_gene}_${mouse_gene}
    """
}

workflow {
    gene_pairs_ch = Channel.fromPath(params.gene_pairs, checkIfExists: true)

    fetched = fetchAllCds(gene_pairs_ch)

    // Manifest -> one (human_gene, mouse_gene, cds_fasta) tuple per successfully
    // fetched pair. Parsed as plain TSV text (not Nextflow's splitCsv operator,
    // which expects a channel, not a single Path inside a closure).
    pair_ch = fetched.cds_dir.flatMap { dir ->
        def manifest = file("${dir}/fetch_manifest.tsv")
        def lines = manifest.readLines()
        if (lines.size() < 2) return []
        def header = lines[0].split('\t')
        lines.drop(1).findResults { line ->
            def cols = line.split('\t', -1)
            def row = [header, cols].transpose().collectEntries { k, v -> [(k): v] }
            if (row.status != 'ok') return null
            tuple(row.human_gene, row.mouse_gene, file("${dir}/${row.human_gene}__${row.mouse_gene}.cds.fa"))
        }
    }

    omega_ch = computeOmega(pair_ch)

    omega_ch
        .collectFile(name: 'omega_results.tsv', storeDir: params.outdir, keepHeader: true, skip: 1, sort: true)
        .subscribe { f -> log.info "Wrote ${f}" }
}
